### ISSUE TITLE
HTTP 400 Bad Request

### ISSUE THREAD

**Issue by Anasthase** [emergentdotorg/shaman#3]
Occurs when doing a query with "older" and/or "newer" parameters in the url, on devices with a locale in wich the decimal separator is not the dot (french for instance, but many more exists).

This is due to the conversion of a double to a string using String.format(), which seems to use the current locale decimal separator.

Quick fix: in WeaveUtil.java, in method toModifiedTimeString, change:

String retval = String.format("%.2f", timed);
to:
String retval = String.format(Locale.ENGLISH, "%.2f", timed);

**Comment by pwoodworth** [comment]
Fixed on master and it should be in the next release after Shaman v1.1.2.  Thanks for the fix!
